# 파일 규격 버전
version: "3"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services: 
  # 서비스 명
  cache:
    # 사용할 이미지
    image: memcached
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 이름 설정
    container_name: aspnet-memcached
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "11221:11221"
  db-prod:
    image: mysql:5.7.34
    restart: always
    container_name : asp-net-mysql-prod
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=backend-prod
      - MYSQL_ROOT_PASSWORD=111111
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  db-dev:
    image: mysql:5.7.34
    restart: always
    container_name : asp-net-mysql-dev
    ports:
      - "3366:3366"
    environment:
      - MYSQL_DATABASE=backend-dev
      - MYSQL_ROOT_PASSWORD=111111
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci