# 파일 규격 버전
version: "3"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services: 
  # 서비스 명
  cache:
    # 사용할 이미지
    image: memcached
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 이름 설정
    container_name: aspnet-memcached
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "11211:11211"
  db:
    image: mysql:5.7.34
    restart: always
    container_name : asp-netmysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=myService
      - MYSQL_ROOT_PASSWORD=111111
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci